[package]
name = "tagged-pointer"
version = "0.1.0"
authors = ["taylor.fish <contact@taylor.fish>"]
edition = "2018"
description = "Platform-independent space-efficient tagged pointers"
documentation = "https://docs.rs/tagged-pointer"
readme = "misc/crate-readme.md"
repository = "https://github.com/taylordotfish/tagged-pointer"
license = "GPL-3.0-or-later"
keywords = ["pointer", "tag"]
categories = ["data-structures", "no-std"]

[dependencies]
typenum = "1.13"

[features]
fallback = []
